backend:
  name: github
  repo: hosseinsaadati/hossein-saadati.github.io
  branch: main

media_folder: "images/uploads"

collections:
  - name: "articles"
    label: "مقالات"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "عنوان مقاله", name: "title", widget: "string"}
      - {label: "تگ / دسته‌بندی", name: "tag", widget: "string"}
      - {label: "زمان مطالعه", name: "readtime", widget: "string", default: "۵ دقیقه مطالعه"}
      - {label: "تاریخ انتشار", name: "date", widget: "string"}
      - {label: "متن مقاله", name: "body", widget: "markdown"}
      - {label: "انتشار؟", name: "published", widget: "boolean", default: true}
